// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WebApplication3.ContextHelpers;

namespace WebApplication3.Migrations
{
    [DbContext(typeof(NewCollegeDBContext))]
    [Migration("20171125061900_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication3.ContextHelpers.Building", b =>
                {
                    b.Property<string>("BuildingName");

                    b.Property<string>("CollegeName");

                    b.Property<string>("City");

                    b.Property<string>("StreetAddress");

                    b.HasKey("BuildingName", "CollegeName");

                    b.HasIndex("CollegeName");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("WebApplication3.ContextHelpers.College", b =>
                {
                    b.Property<string>("CollegeName")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Established");

                    b.HasKey("CollegeName");

                    b.ToTable("Colleges");
                });

            modelBuilder.Entity("WebApplication3.ContextHelpers.Room", b =>
                {
                    b.Property<string>("RoomID");

                    b.Property<string>("BuildingName");

                    b.Property<string>("CollegeName");

                    b.Property<int>("SeatingCapacity");

                    b.HasKey("RoomID", "BuildingName", "CollegeName");

                    b.HasAlternateKey("BuildingName", "CollegeName", "RoomID");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("WebApplication3.ContextHelpers.Building", b =>
                {
                    b.HasOne("WebApplication3.ContextHelpers.College", "College")
                        .WithMany("Buildings")
                        .HasForeignKey("CollegeName")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("WebApplication3.ContextHelpers.Room", b =>
                {
                    b.HasOne("WebApplication3.ContextHelpers.Building", "Building")
                        .WithMany("Rooms")
                        .HasForeignKey("BuildingName", "CollegeName")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
